### ISSUE TITLE
Create instructions for inexperienced users

### ISSUE THREAD

**Issue by Andredroner1** [IkarosKurtz/WorldNavigator#1]
Good afternoon!

You don't have much information for inexperienced users. Could you please describe the idea of your project in more detail with examples of use in Ren'Py? Also, it would be helpful if you could publish a blank Ren'Py project that shows in the simplest way how to use an action and provide a downloadable version.

Thanks in advance!

**Comment by IkarosKurtz** [comment]
I’m currently working on a downloadable demo so you can try it out and explore its level of customization. I'm also updating the README to make it more detailed and clarify aspects that aren't explained very well.

**Comment by IkarosKurtz** [comment]
The WorldNavigator demo is now available in the [release](https://github.com/IkarosKurtz/WorldNavigator/releases/tag/1.0.0) section. I’ve also added a `.rar` file with the necessary files to use it in any project. 

Additionally, new documentation for Ren'Py has been added. Check it out [here](https://github.com/IkarosKurtz/WorldNavigator/blob/main/RENPY.md).
